# -*- encoding: utf-8 -*-

=begin
#TTM for Jira

#Tricentis Test Management for Jira

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

$:.push File.expand_path("../lib", __FILE__)
require "tricentis_tm_api/version"

Gem::Specification.new do |s|
  s.name        = "tricentis_tm_api"
  s.version     = TricentisTmApi::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Swagger-Codegen"]
  s.email       = [""]
  s.homepage    = "https://github.com/swagger-api/swagger-codegen"
  s.summary     = "TTM for Jira Ruby Gem"
  s.description = "Tricentis Test Management for Jira"
  s.license     = "Unlicense"
  s.required_ruby_version = "3.0"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
