=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TricentisTmApi::CyclesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CyclesApi' do
  before do
    # run before each test
    @api_instance = TricentisTmApi::CyclesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CyclesApi' do
    it 'should create an instance of CyclesApi' do
      expect(@api_instance).to be_instance_of(TricentisTmApi::CyclesApi)
    end
  end

  # unit tests for v1_projects_project_key_cycles_post
  # Create cycle(s).
  # ## Create cycle(s).  ##### Note: Release versions are managed in Jira.                #### Body fields:  * **cycles** _(mandatory)_: Provide a list of cycles, with each test having the following fields:      * **name** _(mandatory)_: name of the cycle.      * **version** _(optional)_: cycle&#39;s version (if not provided the version will be under &#39;unversioned&#39;).      * **assignee** _(optional)_: the username which the cycle will be assigned to.      * **plannedStartDate** _(optional)_: the cycle planned start date.      * **plannedEndDate** _(optional)_: the cycle planned end date.      * **fields** _(optional)_: list of fields of the cycle.      Only Environments and Builds are allowed. AllowedValueName must be provided.          * **schemeName** _(mandatory)_: the scheme name of the field (for example Environments).          * **allowedValueName** _(mandatory)_: the allowed value of the scheme (for example Development).
  # @param project_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<V1ProjectsProjectKeyCyclesPostRequestInner>] :v1_projects_project_key_cycles_post_request_inner cyclesApiData.
  # @return [Array<V1ProjectsProjectKeyCyclesPost200ResponseInner>]
  describe 'v1_projects_project_key_cycles_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
