=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TricentisTmApi::FoldersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FoldersApi' do
  before do
    # run before each test
    @api_instance = TricentisTmApi::FoldersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FoldersApi' do
    it 'should create an instance of FoldersApi' do
      expect(@api_instance).to be_instance_of(TricentisTmApi::FoldersApi)
    end
  end

  # unit tests for v1_projects_project_key_folders_post
  # Create folder(s).
  # ## Create new folders. The body contains a list of folders to create.                #### Body fields:                * **name**: The folder name.  * **parentId** _(optional)_: The ID of the parent folder where the new folder should be located.
  # @param project_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<V1ProjectsProjectKeyFoldersPostRequestInner>] :v1_projects_project_key_folders_post_request_inner List of folders to create.
  # @return [V1ProjectsProjectKeyFoldersPost200Response]
  describe 'v1_projects_project_key_folders_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
