=begin
#TTM for Jira

#Tricentis Test Management for Jira

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'

# Unit tests for TricentisTmApi::FoldersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FoldersApi' do
  before do
    # run before each test
    @instance = TricentisTmApi::FoldersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FoldersApi' do
    it 'should create an instance of FoldersApi' do
      expect(@instance).to be_instance_of(TricentisTmApi::FoldersApi)
    end
  end

  # unit tests for v1_projects_project_key_folders_post
  # Create folder(s).
  # ## Create new folders. The body contains a list of folders to create.                #### Body fields:                * **name**: The folder name.  * **parentId** _(optional)_: The ID of the parent folder where the new folder should be located.
  # @param project_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<ProjectkeyFoldersBody>] :body List of folders to create.
  # @return [InlineResponse200]
  describe 'v1_projects_project_key_folders_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
