=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TricentisTmApi::ProjectsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProjectsApi' do
  before do
    # run before each test
    @api_instance = TricentisTmApi::ProjectsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectsApi' do
    it 'should create an instance of ProjectsApi' do
      expect(@api_instance).to be_instance_of(TricentisTmApi::ProjectsApi)
    end
  end

  # unit tests for v1_projects_get
  # Get Jira project(s).
  # ## Get or retrieve Jira project(s).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :keys keys.
  # @option opts [Integer] :offset Numeric value that determines that the result list will start from result #N (zero based)
  # @option opts [Integer] :limit Numeric value that determines that maximum N results will be returned
  # @return [Array<V1ProjectsGet200ResponseInner>]
  describe 'v1_projects_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
