=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TricentisTmApi::RequirementsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RequirementsApi' do
  before do
    # run before each test
    @api_instance = TricentisTmApi::RequirementsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RequirementsApi' do
    it 'should create an instance of RequirementsApi' do
      expect(@api_instance).to be_instance_of(TricentisTmApi::RequirementsApi)
    end
  end

  # unit tests for v1_projects_project_key_test_cases_key_requirement_link_post
  # Link Requirements to test case.
  # ## LLink Requirements to test case.                #### Body fields:  * **issueKey** _(mandatory)_: the issue key.
  # @param key jiraTestKey.
  # @param project_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<V1ProjectsProjectKeyTestCasesKeyRequirementLinkPostRequestInner>] :v1_projects_project_key_test_cases_key_requirement_link_post_request_inner requirements to link.
  # @return [Array<V1ProjectsProjectKeyTestCasesKeyRequirementsPost200ResponseInner>]
  describe 'v1_projects_project_key_test_cases_key_requirement_link_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v1_projects_project_key_test_cases_key_requirements_post
  # Create Requirements and link to test case.
  # ## Create Requirements and link to test case.  ##### Note: In case issue type won&#39;t be provided, default value will be \&quot;Bug\&quot; issue type.                #### Body fields:  * **summary** _(mandatory)_: the requirement summary.  * **description** _(optional)_: the requirement description.  * **issueType** _(optional)_: the requirement issue type (for example: Task, Bug, etc..).
  # @param key jiraTestKey.
  # @param project_key 
  # @param [Hash] opts the optional parameters
  # @option opts [Array<V1ProjectsProjectKeyTestCasesKeyRequirementsPostRequestInner>] :v1_projects_project_key_test_cases_key_requirements_post_request_inner requirements to create.
  # @return [Array<V1ProjectsProjectKeyTestCasesKeyRequirementsPost200ResponseInner>]
  describe 'v1_projects_project_key_test_cases_key_requirements_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
