=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for TricentisTmApi::StatusApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatusApi' do
  before do
    # run before each test
    @api_instance = TricentisTmApi::StatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatusApi' do
    it 'should create an instance of StatusApi' do
      expect(@api_instance).to be_instance_of(TricentisTmApi::StatusApi)
    end
  end

  # unit tests for v1_api_key_is_alive_head
  # Validate if api key is still valid.
  # ## Validate if api key is still valid.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_api_key_is_alive_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
