=begin
#TTM for Jira

#Tricentis Test Management for Jira

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'

# Unit tests for TricentisTmApi::StatusApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StatusApi' do
  before do
    # run before each test
    @instance = TricentisTmApi::StatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatusApi' do
    it 'should create an instance of StatusApi' do
      expect(@instance).to be_instance_of(TricentisTmApi::StatusApi)
    end
  end

  # unit tests for v1_api_key_is_alive_head
  # Validate if api key is still valid.
  # ## Validate if api key is still valid.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v1_api_key_is_alive_head test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
