=begin
#TTM for Jira

#Tricentis Test Management for Jira

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::InlineResponse400
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineResponse400' do
  before do
    # run before each test
    @instance = TricentisTmApi::InlineResponse400.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineResponse400' do
    it 'should create an instance of InlineResponse400' do
      expect(@instance).to be_instance_of(TricentisTmApi::InlineResponse400)
    end
  end
end
