=begin
#TTM for Jira

#Tricentis Test Management for Jira

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::TestrunsSearchBody
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TestrunsSearchBody' do
  before do
    # run before each test
    @instance = TricentisTmApi::TestrunsSearchBody.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TestrunsSearchBody' do
    it 'should create an instance of TestrunsSearchBody' do
      expect(@instance).to be_instance_of(TricentisTmApi::TestrunsSearchBody)
    end
  end
  describe 'test attribute "cycles"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "keys"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "expand"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
