=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1ProjectsProjectKeyImportExecutionJunitPostRequestTestsuiteInnerTestcaseInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TricentisTmApi::V1ProjectsProjectKeyImportExecutionJunitPostRequestTestsuiteInnerTestcaseInner do
  let(:instance) { TricentisTmApi::V1ProjectsProjectKeyImportExecutionJunitPostRequestTestsuiteInnerTestcaseInner.new }

  describe 'test an instance of V1ProjectsProjectKeyImportExecutionJunitPostRequestTestsuiteInnerTestcaseInner' do
    it 'should create an instance of V1ProjectsProjectKeyImportExecutionJunitPostRequestTestsuiteInnerTestcaseInner' do
      expect(instance).to be_instance_of(TricentisTmApi::V1ProjectsProjectKeyImportExecutionJunitPostRequestTestsuiteInnerTestcaseInner)
    end
  end
  describe 'test attribute "failure"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "skipped"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "system_error"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "system_out"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "classname"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "owned_by"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "owner_email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
