=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1ProjectsProjectKeyTestRunsTestRunKeyAttachmentsPostRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TricentisTmApi::V1ProjectsProjectKeyTestRunsTestRunKeyAttachmentsPostRequest do
  let(:instance) { TricentisTmApi::V1ProjectsProjectKeyTestRunsTestRunKeyAttachmentsPostRequest.new }

  describe 'test an instance of V1ProjectsProjectKeyTestRunsTestRunKeyAttachmentsPostRequest' do
    it 'should create an instance of V1ProjectsProjectKeyTestRunsTestRunKeyAttachmentsPostRequest' do
      expect(instance).to be_instance_of(TricentisTmApi::V1ProjectsProjectKeyTestRunsTestRunKeyAttachmentsPostRequest)
    end
  end
  describe 'test attribute "file_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mime_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
