=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1ProjectsProjectKeyTestCasesRequirementsPost200ResponseInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TricentisTmApi::V1ProjectsProjectKeyTestCasesRequirementsPost200ResponseInner do
  let(:instance) { TricentisTmApi::V1ProjectsProjectKeyTestCasesRequirementsPost200ResponseInner.new }

  describe 'test an instance of V1ProjectsProjectKeyTestCasesRequirementsPost200ResponseInner' do
    it 'should create an instance of V1ProjectsProjectKeyTestCasesRequirementsPost200ResponseInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(TricentisTmApi::V1ProjectsProjectKeyTestCasesRequirementsPost200ResponseInner)
    end
  end

  describe 'test attribute "summary"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "issue_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "not_linked_requirement"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "linked_requirement"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
