=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1ProjectsGet200ResponseInnerAvatarUrls
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TricentisTmApi::V1ProjectsGet200ResponseInnerAvatarUrls do
  let(:instance) { TricentisTmApi::V1ProjectsGet200ResponseInnerAvatarUrls.new }

  describe 'test an instance of V1ProjectsGet200ResponseInnerAvatarUrls' do
    it 'should create an instance of V1ProjectsGet200ResponseInnerAvatarUrls' do
      expect(instance).to be_instance_of(TricentisTmApi::V1ProjectsGet200ResponseInnerAvatarUrls)
    end
  end
  describe 'test attribute "x_small"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "small"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "medium"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "large"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
