=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1ProjectsProjectKeyJobsJobIdGet200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TricentisTmApi::V1ProjectsProjectKeyJobsJobIdGet200Response do
  let(:instance) { TricentisTmApi::V1ProjectsProjectKeyJobsJobIdGet200Response.new }

  describe 'test an instance of V1ProjectsProjectKeyJobsJobIdGet200Response' do
    it 'should create an instance of V1ProjectsProjectKeyJobsJobIdGet200Response' do
      expect(instance).to be_instance_of(TricentisTmApi::V1ProjectsProjectKeyJobsJobIdGet200Response)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["Pending", "InProgress", "Completed", "Failed"])
      # validator.allowable_values.each do |value|
      #   expect { instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "issues"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
