=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1ProjectsProjectKeyTestCasesKeyPutRequestTtmFieldsStepsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TricentisTmApi::V1ProjectsProjectKeyTestCasesKeyPutRequestTtmFieldsStepsInner do
  let(:instance) { TricentisTmApi::V1ProjectsProjectKeyTestCasesKeyPutRequestTtmFieldsStepsInner.new }

  describe 'test an instance of V1ProjectsProjectKeyTestCasesKeyPutRequestTtmFieldsStepsInner' do
    it 'should create an instance of V1ProjectsProjectKeyTestCasesKeyPutRequestTtmFieldsStepsInner' do
      expect(instance).to be_instance_of(TricentisTmApi::V1ProjectsProjectKeyTestCasesKeyPutRequestTtmFieldsStepsInner)
    end
  end
  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expected_result"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
