=begin
#TTM for Jira

#Tricentis Test Management for Jira

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1ProjectsProjectKeyCyclesPostRequestInnerFieldsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe TricentisTmApi::V1ProjectsProjectKeyCyclesPostRequestInnerFieldsInner do
  let(:instance) { TricentisTmApi::V1ProjectsProjectKeyCyclesPostRequestInnerFieldsInner.new }

  describe 'test an instance of V1ProjectsProjectKeyCyclesPostRequestInnerFieldsInner' do
    it 'should create an instance of V1ProjectsProjectKeyCyclesPostRequestInnerFieldsInner' do
      expect(instance).to be_instance_of(TricentisTmApi::V1ProjectsProjectKeyCyclesPostRequestInnerFieldsInner)
    end
  end
  describe 'test attribute "scheme_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "scheme_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["List", "String"])
      # validator.allowable_values.each do |value|
      #   expect { instance.scheme_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "scheme_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "allowe_value_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "allowed_value_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
