=begin
#TTM for Jira

#Tricentis Test Management for Jira

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1projectsprojectkeytestrunsFields
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'V1projectsprojectkeytestrunsFields' do
  before do
    # run before each test
    @instance = TricentisTmApi::V1projectsprojectkeytestrunsFields.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V1projectsprojectkeytestrunsFields' do
    it 'should create an instance of V1projectsprojectkeytestrunsFields' do
      expect(@instance).to be_instance_of(TricentisTmApi::V1projectsprojectkeytestrunsFields)
    end
  end
  describe 'test attribute "scheme_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "scheme_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["List", "String"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.scheme_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "scheme_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "allowe_value_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "allowed_value_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
