=begin
#TTM for Jira

#Tricentis Test Management for Jira

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TricentisTmApi::V1projectsprojectkeytestcaseskeyTtmFieldsSteps
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'V1projectsprojectkeytestcaseskeyTtmFieldsSteps' do
  before do
    # run before each test
    @instance = TricentisTmApi::V1projectsprojectkeytestcaseskeyTtmFieldsSteps.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V1projectsprojectkeytestcaseskeyTtmFieldsSteps' do
    it 'should create an instance of V1projectsprojectkeytestcaseskeyTtmFieldsSteps' do
      expect(@instance).to be_instance_of(TricentisTmApi::V1projectsprojectkeytestcaseskeyTtmFieldsSteps)
    end
  end
  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "expected_result"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
