=begin
#TTM for Jira

#Tricentis Test Management for Jira

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.50
=end

# Common files
require 'tricentis_tm_api/api_client'
require 'tricentis_tm_api/api_error'
require 'tricentis_tm_api/version'
require 'tricentis_tm_api/configuration'

# Models
require 'tricentis_tm_api/models/inline_response_200'
require 'tricentis_tm_api/models/inline_response_200_1'
require 'tricentis_tm_api/models/inline_response_200_2'
require 'tricentis_tm_api/models/inline_response_200_2_custom_fields'
require 'tricentis_tm_api/models/inline_response_200_2_items'
require 'tricentis_tm_api/models/inline_response_200_2_ttm_fields'
require 'tricentis_tm_api/models/inline_response_200_3'
require 'tricentis_tm_api/models/inline_response_200_3_element_data_errors'
require 'tricentis_tm_api/models/inline_response_200_3_errors'
require 'tricentis_tm_api/models/inline_response_200_3_issues'
require 'tricentis_tm_api/models/inline_response_200_4'
require 'tricentis_tm_api/models/inline_response_200_5'
require 'tricentis_tm_api/models/inline_response_200_6'
require 'tricentis_tm_api/models/inline_response_200_7'
require 'tricentis_tm_api/models/inline_response_200_8'
require 'tricentis_tm_api/models/inline_response_200_9'
require 'tricentis_tm_api/models/inline_response_200_items'
require 'tricentis_tm_api/models/inline_response_202'
require 'tricentis_tm_api/models/inline_response_400'
require 'tricentis_tm_api/models/key_automation_body'
require 'tricentis_tm_api/models/key_requirements_body'
require 'tricentis_tm_api/models/projectkey_folders_body'
require 'tricentis_tm_api/models/projectkey_testcases_body'
require 'tricentis_tm_api/models/projectkey_testruns_body'
require 'tricentis_tm_api/models/requirement_link_body'
require 'tricentis_tm_api/models/stepnumber_attachments_body'
require 'tricentis_tm_api/models/testcases_key_body'
require 'tricentis_tm_api/models/testcases_search_body'
require 'tricentis_tm_api/models/testrunkey_attachments_body'
require 'tricentis_tm_api/models/testruns_search_body'
require 'tricentis_tm_api/models/testruns_testrunkey_body'
require 'tricentis_tm_api/models/v1projects_avatar_urls'
require 'tricentis_tm_api/models/v1projectsprojectkeytestcases_automation'
require 'tricentis_tm_api/models/v1projectsprojectkeytestcases_fields'
require 'tricentis_tm_api/models/v1projectsprojectkeytestcases_tests'
require 'tricentis_tm_api/models/v1projectsprojectkeytestcases_ttm_fields'
require 'tricentis_tm_api/models/v1projectsprojectkeytestcases_ttm_fields_steps'
require 'tricentis_tm_api/models/v1projectsprojectkeytestcaseskey_fields'
require 'tricentis_tm_api/models/v1projectsprojectkeytestcaseskey_ttm_fields'
require 'tricentis_tm_api/models/v1projectsprojectkeytestcaseskey_ttm_fields_steps'
require 'tricentis_tm_api/models/v1projectsprojectkeytestruns_automation'
require 'tricentis_tm_api/models/v1projectsprojectkeytestruns_cycle'
require 'tricentis_tm_api/models/v1projectsprojectkeytestruns_cycle_version'
require 'tricentis_tm_api/models/v1projectsprojectkeytestruns_fields'
require 'tricentis_tm_api/models/v1projectsprojectkeytestruns_steps'
require 'tricentis_tm_api/models/v1projectsprojectkeytestruns_steps_1'
require 'tricentis_tm_api/models/v1projectsprojectkeytestruns_test_runs'

# APIs
require 'tricentis_tm_api/api/attachments_api'
require 'tricentis_tm_api/api/defects_api'
require 'tricentis_tm_api/api/folders_api'
require 'tricentis_tm_api/api/projects_api'
require 'tricentis_tm_api/api/requirements_api'
require 'tricentis_tm_api/api/status_api'
require 'tricentis_tm_api/api/test_cases_api'
require 'tricentis_tm_api/api/test_runs_api'

module TricentisTmApi
  class << self
    # Customize default settings for the SDK using block.
    #   TricentisTmApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
